server:
#  port: 8080
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: changeit
    keyStoreType: PKCS12
    keyAlias: tomcat

logging:
  level:
    root: INFO
    pl.itacademy: DEBUG

spring:
  profiles:
    active: dev
